### PR TITLE
Added compat for Alpha Mythology

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
Also requires #285, as it uses problematic stuff from Vanilla Expanded Framework (the method `VanillaCookingExpanded.Thought_Hediff:MoodOffset`)

### CODE REVIEW

**Comment by notfood** [comment]
Oops.

**Comment by notfood** [comment]
Was too quick to hit on merge, I reverted it. Will wait for #285

**Comment by SokyranTheDragon** [comment]
Honestly, it was fine to keep. The patch isn't directly related to code from it, as the issue with the mod comes from VEF.

**Comment by notfood** [comment]
Readded as #288

**Pull request merged**
