### PR TITLE
Added compat for Hemogen Extractor

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
Requires rwmt/MultiplayerAPI#9 and rwmt/Multiplayer#381

Sadly, not really possible to make a simple patch without those changes. It could (in theory) be possible without it, but it would require quite a bit of work and implementing a lot of workarounds.

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
Updated Hemogen Extractor compat. Again the case of a compat waiting for API update.

Now uses the changed API introduced by Zetrith, instead of the (now outdated) ones made by me.

**Comment by notfood** [comment]
Is merge ok?

**Comment by SokyranTheDragon** [comment]
Not yet safe, needs rwmt/MultiplayerAPI#10 to be up on NuGet as well as Multiplayer to implement the new API.

**Comment by SokyranTheDragon** [comment]
Should be safe to merge. Also, just in case - merged master branch in.

**Pull request merged**
