### PR TITLE
Fixed/remade compat for Gastronomy

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
Waiting for MP API update, as well as Multiplayer update to include support for the new API.

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
And as a side note - making this a compat with reference to original mod was require due to having to extend the `ThingFilterContext` record. We technically could have used a different type there (like `object` or `IExposable`, but it needs a SyncWorker which will work for our type.

And now that I think about it, I could have worked around it by making a wrapper class to the object we store there. But since the compat is already done, I'm not gonna go digging in there right away.

**Comment by SokyranTheDragon** [comment]
Updated Gastronomy compat. Again the case of a compat waiting for API update.

Requires CashRegister to also be referenced.

Now uses the changed API introduced by Zetrith, instead of the (now outdated) ones made by me.

Includes a couple of fixes. It may possibly need more in the future, but for now it seemed stable (unless something changed recently with the mod).

**Comment by notfood** [comment]
Can it be merged?

**Comment by SokyranTheDragon** [comment]
Still needs the new API for thing filters.

**Comment by SokyranTheDragon** [comment]
Should be safe to merge. Also, just in case - merged master branch in.

**Pull request merged**
