### PR TITLE
Compat for Vehicle Framework

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
Currently only a draft PR, as the patch is not fully complete. Will need further additions to MP API to be feasible to complete (dialog session, persistent dialogs) as there's a few dialogs similar to the ones from vanilla, but specifically made to handle vehicles as well.

Also, as of right now only tested on the current Workshop release - use with VF unstable release on your own risk.

Patch progress:

- [x] Single-map multithreading - technically done, but needs testing if actually needed (so currently commented-out)
- [x] Global/world multithreading - likely not needed
- [x] Coroutines - likely not needed
- [x] Normal/generic gizmos (turn/draft the vehicle toggle, a bunch of dev mode gizmos, etc.)
- [x] Turret gizmo (targetting, cancelling attacks, reloading, etc.)
- [x] RNG - a couple of motes using `GenView.ShouldSpawnMotesAt` without push/pop
- [x] Vehicle color dialog - opened locally only, result synced when accepted
- [x] Vehicle naming dialog - sets the name on a vehicle pawn the same way vanilla handles it, synced through MP itself
- [x] TransferableVehicleWidget, Dialog_AssignSeats - only used by Dialog_FormVehicleCaravan
- [x] Form vehicle caravan dialog (Dialog_FormVehicleCaravan)
- [x] Load cargo dialog (Dialog_LoadCargo)
- [x] Aerial vehicle trade (Dialog_TradeAerialVehicle) - not needed, unused by the mod and marked obsolete
- [x] Vehicle's cargo tab - both local map and world tab should be patched, as they generally share the same code
- [x] ITab_Vehicle_Upgrades - will need patching in the future, but currently unused/unfinished
- [x] WITab_AerialVehicle_Health - check if anything needs patching, but likely not
- [x] WITab_AerialVehicle_Items, AerialVehicleTabHelper - abandoning items, etc.
- [x] Aerial launch - LaunchProtocol, possibly the ___Takeoff classes as well
- [ ] Possibly other stuff which I haven't seen or haven't realized need patching yet

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
Just dropped a new commit to the PR with following changes:

- Requires update to the API changes for sessions (rwmt/Multiplayer#401 and rwmt/MultiplayerAPI#11)
- Turned into a referenced compat, as it was getting hard to manage everything without it, especially to handle sessions (SmashTools had to also be referenced as VehicleFramework was referencing it which caused issues)
- Almost fully patches the vehicle caravan forming dialog using the new API (took several days of work to get it working)
- Partially patched cargo loading dialog using the new API
- Multithreading patch was re-enabled again, as I was able to verify it's needed
- 2 multithreading methods aren't patched, as they (as far as I'm aware) are safe (Vehicles.VehiclePathing)
- 1 multithreading method isn't patched, as I believe it runs once per in-game year and has a high chance of not affecting anything (Vehicles.WorldVehiclePathGrid:RecalculateAllPerceivedPathCosts)
- There is a commented-out patch for pathfinding code that modifies threading to be more MP-safe - sadly, it has issues and had to be disabled
- Removed the temporary MP patch, as it's no longer necessary (the issue got fixed in MP itself)

**Comment by ActuallyALovelyGrave** [comment]
I wish you luck.

**Comment by SokyranTheDragon** [comment]
Finished making session for and patching `Dialog_LoadCargo`.

Also did some improvements to caravan forming session, synced "drop all" interaction in vehicle cargo, and did some other minor cleanup.

**Comment by SokyranTheDragon** [comment]
Also removed "dock boat dialog (Dialog_DockBoat)" from the progress list, as it seems to have been removed (likely was unused/got reworked?)

**Comment by SokyranTheDragon** [comment]
Finishing up flying vehicles syncing right now. Launching them, takeoff, etc. are mostly done and ready. Stuff that needs to be finished for them:

- Landing in non-loaded maps on specific cells (partially done)
  - Sync it in such a way that it won't remove the map before actually landing
  - Force pause when there's a map loaded with a vehicle that needs to land
- When launching from a caravan, unselect the caravan and select the flying vehicle
- Make sure the gizmos for flying vehicles work properly

**Comment by SokyranTheDragon** [comment]
Another commit with syncing of aerial vehicles. It should handle all implemented functionality for flying vehicles (unless I've missed something).

Landing on specific tile on maps that aren't loaded at the time was implemented as a session, and will need a bit extra testing (and likely some tweaks).

Updated language files related to aerial vehicles session, as well as cargo loading session (as I forgot to include it earlier).

Also some minor (mostly automatic) formatting changes.

**Comment by SokyranTheDragon** [comment]
Should now be fully compatible. Currently, only waiting for the API update, so switching from a draft PR to a PR with "waiting on merge" label.

Some recent changes:
- Aerial vehicle tab is synced (leaving behind items and banishing pawns)
- Added a "Switch to map" button to dialogs
- Fixed errors with current unstable VF release (untested)
- Changed code and comments from "Targetter" to "Targeter"

**Comment by SokyranTheDragon** [comment]
One thing I forgot about - this will require #393

**Comment by SokyranTheDragon** [comment]
Looks like a new update for Vehicle Framework released which broke the compat a bit, working on fix.

**Comment by SokyranTheDragon** [comment]
Should be fixed now

**Comment by notfood** [comment]
Merge ok?

**Comment by SokyranTheDragon** [comment]
Still needs the API update.

**Comment by SokyranTheDragon** [comment]
Found some issues with mutation tracing - specifically, using turrets while moving. I've missed this due to me just... not using vehicle turrets while moving, ever... Oops.

**Comment by SokyranTheDragon** [comment]
Fixed the issue caused by turret rotation. Basically:

- Turret rotation is recalculated both during ticking and drawing the turret
- This patch prevents the turret rotation from changing during drawing (along with few other patches)
- Ticking happens conditionally, so due to the drawing no longer updating the turret rotation it'll cause it to no longer change unless also ticking
- This causes issues where a vehicle drives around and changes its rotation, as the turret won't update its rotation
- So this patch also includes a patch to update turret rotations every tick to prevent that issue

Also, looking into a few other possible issues with the mod. But the fixes will come at a later date.

**Pull request merged**
