### PR TITLE
Blueprints: building blueprints in Multiplayer seems to work now.

### PR DESCRIPTION
**Pull request by PapyChacal**
There is still a downside: creating a Blueprint will create it on every connected client, popping the name prompt to saving it on every screen. But I guess this still get this mod's compatibility from 1 to at least, 3.5? 😛 

I tested with 2 clients in Lan, switching materials, rotating, flipping... Everything seems to work when applying a Blueprint.
But I really am a newbie about modding RimWorld: I won't be surprised if there are still some errors with exotic items or whatever!

### CODE REVIEW

**Comment by notfood** [comment]
That `SyncWorkerExtension` doesn't belong to the file. I can't tell if it's being in use either. Can you remove it and just put it in a function? Or what purpose does it serve?

**Comment by PapyChacal** [comment]
I use them everywhere in the file, for example in SyncDesignator_Blueprint (l.118):
  `sync.Write(blueprint, blueprintGetter.Invoke(obj, null));`
  
The present Read and Write methods are generic, so they take a type parameter that must be known at compile-time.
In this example, to sync a Designator_Blueprint (defined in the external mod only), I had to sync its contained Blueprint (defined in the external mod only as well).
Without referencing the external mod, I saw 2 solution:

- Sync Blueprint and other required types in one big SyncWorker for Designator_Blueprint
- Use Read/Write using reflexion, and register specific multiple SyncWorkers that call each other. I chose this, thinking it would be cleaner. But calls quickly became unreadable, and I thought of this interface.

I think offering this way of calling it would be nice. It allows to cleanly handle different types not accessible to Multiplayer-Compatibility in their respective SyncWorkers. Here, when the call given in example is made, it automatically uses the SyncWorker for "Blueprint" which I registered too.

Now off course if this bothers you, I can remove the extensions and simply use a more local helper method. But I think offering such a signature in API or Multiplayer-Compatibility directly would be powerful.

**Comment by notfood** [comment]
The thing about reflection is that it's super expensive performance wise. On the write/read method, that you call every time you need to send/receive data, it's way too expensive. Someone else may try to use your extension methods and they'll shoot themselves in the foot because the performance hit is huge. Even in your case it has a moderate hit. If you want to use it it's fine, but don't make it an extension method for others to shoot themselves.

**Comment by PapyChacal** [comment]
Okay, I get your point and I will remove the extension. I will change the implementation, so reflection is only used at initialization, then the new Read/Write methods get reused when called.
To be sure: if this useless overhead is solved, are you still not interested in having this in the API?

**Comment by PapyChacal** [comment]
I dug a bit, and I think the best way performance-wise and in terms of API would be to expose a `SyncWorker.Bind<T>(ref T obj, SyncType type)` method (And its Read/Write equivalents). This signature is already present in WritingSyncWorker and ReadingSyncWorker (see WritingSyncWorker.cs:21) :

```cs
public void Bind<T>(ref T obj, SyncType type)
{
    SyncSerialization.WriteSyncObject(writer, obj, type);
}
```

It is the call made by the usual Bind<T>(ref T obj) signature (line 26) :
```cs
public override void Bind<T>(ref T obj)
{
   SyncSerialization.WriteSyncObject(writer, obj, typeof(T));
}
```
So this wouldn't cost more than the usual call. The only risk would be users using this new signature for primitive types while they have specialized methods. But they would have to bother typing `Bind(x, typeof(int))` where `Bind(x)` works just fine.

Then, if I understood correctly, one could call `MP.RegisterSyncWorker` for `someType`, and directly call the exposed (not my cheap implementation) `SyncWorker.Read(Type someType)` with no overhead.

It would just be a few more lines in MultiplayerAPI. So unless you already know that you won't have this in MultiplayerAPI, I'll try to do this and make a Pull Request there!

**Comment by notfood** [comment]
Yeah, keep this PR contained for Blueprints. Let's discuss API additions separatedly. We can later change it to whatever.

As for the Bind<T>, I agree, they need to be exposed.

**Comment by PapyChacal** [comment]
I removed the extension methods and used the new API I talked about: rwmt/MultiplayerAPI#3

**Pull request merged**
