### PR TITLE
Progress on updating to 1.1

### PR DESCRIPTION
**Pull request by Nebual**
* Updated project/build process, mirroring the Multiplayer mod
* Remove Assemblies/ from git. These belong in Releases
* Disable Hospitality/GiddyUpBattleMounts, as they're targetting old methods that error on init
* Disable most of SimpleSidearms syncing - I got "Drop weapon" to sync, but I'm unable to figure out how to sync a property modification of `CompSidearmMemory.primaryWeaponMode` changing inside `SimpleSidearms.rimworld.Gizmo_SidearmsList.handleInteraction` - I saw you had a comment 
```
            // This is an exercise of futility testing the limits of the API
            // TODO: Pester modder to encapsulate autoLockOnManualSwap in a method
```
and I agree haha. Probably easier to just PR against their repo than try to do it all via Harmony at runtime without directly linking against the dll...

**Testing:**
- PathAvoid + Vanilla Fishing Expanded works
- Giddyup Ride and Roll doesn't work
- The others I only tested that there's no errors on init/host when those mods are loaded, I don't know em so wasn't sure how to test

### CODE REVIEW

**Comment by Nebual** [comment]
Alpha build: [MultiplayerCompatibility-1.1-alpha1.zip](https://github.com/rwmt/RimWorld-Multiplayer-Compatibility/files/4498405/MultiplayerCompatibility-1.1-alpha1.zip)

**Comment by Cody-Spring** [comment]
Not seeing an "issues" on the fork so leaving it here:

Getting the following error when trying to generate a colony for a new game with GiddyUpRideAndRoll compatch:

Exception from asynchronous event: System.FieldAccessException: Field `Verse.AreaManager:areas' is inaccessible from method `Multiplayer.Compat.GiddyUpRideAndRollCompat:AddStartingAreasPostfix (Verse.AreaManager)'

will look into it myself something in the next few days when I get time, but leaving the info here in case you can get to it before me.

**Comment by Cody-Spring** [comment]
@Nebual Giddy-up now has native compatibility so we can remove those patches, and after a lot of testing Animals Logic and Power Switch are both good now as well, so all we have left in this is to finish up Simple Sidearms

**Comment by LYNXEMS** [comment]
@Cody-Spring #5 added pr for that then...

**Comment by notfood** [comment]
I would like to publish it to steam in the current state, it'll never get to perfect as every other mod is a moving target, so good enough is fine for now.

**Comment by notfood** [comment]
I have published it on steam so it goes to master. Please create independant branches that target master to support new mods.

**Pull request merged**
