### PR TITLE
SYR Set Up Camp Compatibility

### PR DESCRIPTION
**Pull request by Thomas107500**
Tested it with 2 local instances running, it works 90% of the time with sometimes still map desync on generating the camp map which i don't think i am able to fix that because of how the code is written, i hope this PR can at least get the mod from compatibility status 1(not work at all) to 3(mostly work) or 2(partially work)

### CODE REVIEW

**Comment by notfood** [comment]
It needs a transpiler into Camp method, it's using
```csharp
string randomSeed = Find.TickManager.TicksGame.ToString();
```
Which returns different values for every player. Needs to be replaced with TickAbs. That's why it'll fail "sometimes". Anyhow, Syr is open to PRs from the Multiplayer team.

**Comment by Thomas107500** [comment]
Just like I guessed, that's why I don't think I am able to do it :P probably also the map size needed a transpiler coz there is a random there too, also u mean u should do PR there instead of here?

**Comment by notfood** [comment]
Yeah, patching isn't a good idea when the mod moves too fast. Syr loves to update their mods. It's preferable if we can get a PR rolling over there with 100% support.

**Comment by Thomas107500** [comment]
ah i see, but i just checked the mod's repo and it is different from what i see from dnSpy, so i guess it is outdated? so what should i do now?

**Comment by notfood** [comment]
We need to talk to Syr

**Comment by Thomas107500** [comment]
Turns out i am just blind and those files already existed for a few months :P 
Did a PR there and see if it will be accepted, Thanks :D

**Pull request closed without merging**
