### PR TITLE
Updated Vanilla Expanded Framework

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
Synced contract info dialog (requires fixing WorldComponent, either by removing the need or adding a sync worker for World)

Fixed picking the option to hire on comms console (it had 50/50 chance to fail and cause an error)

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
Updated to fix merge conflicts. It could use a pause lock there, as there's 2 dialogs that should be blocking. Definitely not something I'll be doing today. And could possibly be done in a different PR.

**Comment by SokyranTheDragon** [comment]
Merged with master, and made those 2 dialogs use the new dialog closing code.

**Comment by notfood** [comment]
Does it still depend on WorldComponent fix?

**Comment by SokyranTheDragon** [comment]
I'm pretty sure yes, but since we've had the sync worker for `World`, the syncing of `WorldComponent` is now working fine.

https://github.com/rwmt/Multiplayer/commit/9a723b2a64d672747ca4ad5634883e6dec9046d3

**Comment by notfood** [comment]
Should this be closed? Looks outdated

**Comment by SokyranTheDragon** [comment]
I'll check later and close if not needed anymore.

**Comment by SokyranTheDragon** [comment]
From my testing the issues still appear unless those changes are included, so I've merged it with master. All seems to work fine on my end.

**Pull request merged**
