### PR TITLE
Added compat for Vanilla Races Expanded - Phytokin

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
Sync for gizmo to plant a saplingchild relies on rwmt/Multiplayer#372, everything else will work without it.

### CODE REVIEW

**Comment by notfood** [comment]
We can have the temporary syncworkers here until they get merged and released. Just note it so I can find it and remove it.

**Comment by SokyranTheDragon** [comment]
I'll work on it tomorrow then, since it's quite late right now.

**Comment by SokyranTheDragon** [comment]
I realized while working on it - patching for the plant saplingchild gizmo is not needed... I guess my brain noticed that it has effect on gameplay, and I immediately decided it needs patching.

It calls `TryTakeOrderedJob` - which is synced by MP itself - and it does not have any other effect on gameplay besides making the pawn perform the job. The only other thing it does is checks if the terrain is correct for the sapling before starting the job.

**Comment by notfood** [comment]
Does it still need the syncworker?

**Comment by SokyranTheDragon** [comment]
No, not anymore. The method that got removed used it, but no others did.

**Pull request merged**
