### PR TITLE
Fixed and updated MVCF part of Vanilla Expanded Framework

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
The main issue was that VerbManager could be created for one/some, but not all players when clicking on a pawn/animal. This patch fixes it.

Additionally, a list of weak references ended up being a little bit too volatile, so I've decided to make syncing more reliable compared to the original way I handled it.

### CODE REVIEW

**Comment by notfood** [comment]
Dang, looks complex. Is it possible to pre-create the VerbManager instead? Because you want an even state on all players, not just some with it and some without.

**Comment by SokyranTheDragon** [comment]
Most of the places the VerbManager (as far as I can tell) are fine, and seem to be initialized for all players at the same time. There are some however which seem to be only used by things player can interact with (like gizmos), and they are initialized when the player selects a pawn/animal.

We could try to pre-initialize them, but I believe it would require making a bunch of harmony patches, some of which would patch other harmony patches (there are a lot of places those VerbManagers can be initialized), or going through each (some?) animals/pawns and checking if they should have those. I decided the easiest route would be to replace a single offending method, and if it needs to create it then do it in a synced method.

**Comment by notfood** [comment]
The VerbManager can only be initialized once, right? The other places where it can init probably test if it exists first. I feel you should give it a try. It's the same thing that happened to AnimalLogic and beds, it'd init when used so instead I called it before game is even started.

**Comment by legodude17** [comment]
It actually used to init before game start, but sometimes initing the VerbManager needs to spawn something, which can only happen while the game is running and not while spawning other things.

**Comment by notfood** [comment]
Damn weird scenario. Just init the VerbManager on game start and have a hasItSpawnedItYet variable. Is it open source?

**Comment by legodude17** [comment]
Yeah it's open source at https://github.com/AndroidQuazar/VanillaExpandedFramework. The variable is a good idea, may do that.

**Pull request merged**
