### PR TITLE
Stop gameplay logic from being called during UI

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
All the patched methods perform gameplay operations (like adding hediffs) during non-synced/UI code (alert updates, Thought:MoodOffset can be called from it)

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
And just to fully clarify - this fixes desyncs caused by those.

**Comment by notfood** [comment]
I think this method is better as `PatchingUlitilies.CancelOnUI`, it can be stuffed in a region, I don't see it expanding more and it's the role of `PatchingUtilities` to fix methods.

**Comment by SokyranTheDragon** [comment]
Alright, done. Not 100% sure on the naming, so let me know if you'd like me to change something in there.

**Comment by notfood** [comment]
Looks good, I see lots of improvements too.

**Pull request merged**
