### PR TITLE
Update ReGrowthCore

### PR DESCRIPTION
**Pull request by InfernalSkys**
Sync the 'Make Camp' gizmo

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
```csharp
MP.RegisterSyncMethod(type, "MakeCamp");

MpCompat.RegisterLambdaDelegate(type, "Postfix", 0);
```

Both sync the same thing. No point syncing the same thing twice. Just stick to the method itself.

**Comment by InfernalSkys** [comment]
Got it! will do.

**Comment by SokyranTheDragon** [comment]
As to why sync the method and not the delegate:
- Delegates have extra overhead (need to handle syncing the delegate itself, which MP handles automatically - but still needs to do it)
- If a different gizmo ends up calling `MakeCamp`, you don't need to sync that one (although in rare cases this may be undesirable and sync each one separately)

**Comment by InfernalSkys** [comment]
Thanks for the explanation! I've updated the PR accordingly.

**Pull request merged**
