### PR TITLE
Vanilla furniture expanded security patch

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
The artillery for off-map usage still doesn't work, and I don't know how to fix it. I'd appreciate if anyone  with more experience could look at it.

The flamethrower/floodlight turrets (not sure which one) seemed to desync once, but I could not reproduce it and it seems to working as intended besides that.

### CODE REVIEW

**Comment by notfood** [comment]
World stuff is a bit difficult, I'll take a look.

**Comment by notfood** [comment]
The Verse.Mote stuff is because somewhere the mote is being thrown, such direct patch should be in Multiplayer mod, not here. We need to patch where they throw the mote in the mod.

**Comment by notfood** [comment]
By the way, the MPAttribute needs to be chagned to the PackageId

```csharp
[MpCompatFor("VanillaExpanded.VFESecurity")]
```

**Comment by notfood** [comment]
Refer to the changes I made here to update your PR
https://github.com/rwmt/Multiplayer-Compatibility/blob/update-1.1/Source/Mods/VanillaFurnitureExpandedPower.cs

**Comment by SokyranTheDragon** [comment]
Sorry for doing that mess, I'm kinda new and still learning. I didn't really see a way to fix it without patching Vanilla code, but I realized today that I was being dumb 🤦‍♂️

Let me fix that real quick.

**Comment by SokyranTheDragon** [comment]
I've commented out the code in case it would be needed, as it properly synced the gizmos to start targetting a tile (as in it opened the map, assuming we'd want to do that for all players) and to cancel the targetting. It's the part about selecting world tile was causing issues, so I decided to just remove syncing of gizmos for now.

If you, however, believe it should be removed, then I'd be more than happy to do it.

**Comment by SokyranTheDragon** [comment]
I've managed to sync the long range artillery strikes, and tested it for around half an hour. It worked perfectly... With a single exception. 

If the game is saved while the artillery shell is still on the colony map, then it causes a NullPointerException with `VFESecurity.ArtilleryComp.ArtilleryProps` ([original source](https://github.com/AndroidQuazar/VanillaFurnitureExpanded-Security/blob/master/Source/VFESecurity/Comps/WorldObjectComps/ArtilleryComp.cs#L52)). I don't have enough experience to tell what causes this issue, neither do I know how to fix it.

**Comment by notfood** [comment]
I feel that's their own fault for using `cachedArtilleryDef` instead of `ArtilleryDef`, chances are that it reproduces without Multiplayer.

Looks ready for merging.

**Comment by SokyranTheDragon** [comment]
I was not able to reproduce that issue in without Multiplayer on, while it was happening consistently with it enabled. But as I said, I don't really have enough experience to be able to tell more about it.

**Comment by notfood** [comment]
Let's just put a warning not to use that. I can't seem to find a fix.

**Pull request merged**
