### PR TITLE
Patched Vanilla Cooking Expanded

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
I've tested it for around 15 hours and found no issues that were directly connected to this mod

There were some issues I've encountered, like grass causing desync, but they didn't seem to be related to this mod at all

### CODE REVIEW

**Comment by notfood** [comment]
Adding SyncWorkers to the Commands seems iffy, isn't there another way? It's just sending the Thing. TryInsertFirstThing, TryInsertSecondThing, TryInsertThirdThing seems very strange without looking at their code, I'm suspicious.

**Comment by SokyranTheDragon** [comment]
`Command_SetQualityList` has a field `Building_ItemProcessor building`, which is accessed from all the methods inside of the command that are synced. An example of one such method:

```csharp
[CompilerGenerated]
private void <ProcessInput>b__3_0()
{
	this.building.qualityRequested = QualityCategory.Awful;
	this.building.qualityEstablished = true;
}
```

As all the methods are accessing that field I've made SyncWorker for it.


`Command_SetFirstItemList`, etc. are 3 different classes with basically identical structure inside. All of them have fields `Building_ItemProcessor building` and `List<Thing> things`. One of the methods I sync accesses both of these fields, while the other one accesses only `building` field, so again - I made SyncWorker to sync those.

I used `Traverse` as I it provides a way to access fields by name, as opposed by FieldInfo. Using FieldInfo there instead would increase the amount of code I'd have to write, as I'd then do it similarly to how I did it with `Command_SetQualityList`, and make a separate method for each of those classes.


As for the question if this could be made differently - unless it could be somehow done with the MP API that I don't know of - then the only way I could think of is making a Harmony prefix to make a workaround method (while cancelling the original one), which would both require more code, and it would be much less elegant than my current approach.

**Comment by notfood** [comment]
Hate it so much when the coder repeats themselves instead of abstracting it. I went and looked at the source code, almost makes me not want to use it. Add this references on the header for the future:
```xml
<see href="https://github.com/juanosarg/ItemProcessor"/>
<see href="https://github.com/juanosarg/VanillaCookingExpanded"/>
```
Your code is fine. I think it'd be better if we PR some changes to them though.

**Comment by SokyranTheDragon** [comment]
I haven't realized this mod was on Git. Vanilla Expanded mods are inconsistent with that, as some are unavailable there, so I just assumed I wouldn't find it there.

I'll add both links to the header soon.

**Pull request merged**
